# Generated by Django 4.0 on 2023-10-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AG', 'Agendado'), ('NA', 'Nao atendido'), ('A', 'Atendido'), ('NAS', 'Nao atendido (sem cobrança)'), ('R', 'Remarcar'), ('F', 'Faltou'), ('PC', 'Presença confirmada'), ('C', 'Cancelado')], max_length=4)),
                ('detalhes', models.CharField(max_length=155)),
                ('dt_atend', models.DateTimeField(auto_now_add=True, null=True)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('celular_atd', models.CharField(max_length=155)),
                ('lembrete_sms', models.CharField(max_length=155)),
                ('lembrete_wpp', models.CharField(max_length=155)),
                ('dt_inicio', models.DateTimeField(auto_now_add=True)),
                ('dt_fim', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimentos.area')),
                ('convenio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimentos.convenio')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='authentication.account')),
                ('procedimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimentos.procedimento')),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profissional', to='authentication.account')),
                ('sala', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='atendimentos.sala')),
            ],
        ),
    ]
