# Generated by Django 4.0 on 2023-10-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('celular', models.CharField(max_length=155)),
                ('dt_nasc', models.DateTimeField(auto_now_add=True, null=True)),
                ('cpf', models.CharField(max_length=155)),
                ('cidade', models.CharField(max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('O', 'Outro')], max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
