# Generated by Django 4.0 on 2023-10-16 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_contato', models.CharField(blank=True, max_length=100)),
                ('tipo_contato', models.CharField(blank=True, choices=[('E', 'Email'), ('T', 'Telefone'), ('C', 'Celular')], max_length=1)),
                ('contato', models.CharField(blank=True, max_length=100)),
                ('id_ref', models.CharField(blank=True, max_length=100)),
                ('ref', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=155)),
                ('cargo', models.CharField(max_length=155)),
                ('tipo', models.BooleanField(default=False)),
                ('permissao', models.JSONField(default=None)),
                ('colaborador', models.BooleanField(default=False)),
                ('dt_nasc', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_ref', models.CharField(max_length=155)),
                ('ref', models.CharField(max_length=155)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
